#!/bin/bash

cd /tmp

WORKDIR=$(mktemp -d)

cd "$WORKDIR"

echo "Downloading sources..."

# gtkdialog (main branch)
wget -O gearlever.zip \
  https://github.com/mijorus/gearlever/archive/refs/heads/master.zip

echo "Extracting..."
unzip gearlever.zip

pip install desktop-entry-lib --prefix=/usr --no-input --exists-action i --quiet

echo "Building gearlever..."
cd "gearlever-master"
meson --buildtype=release --prefix=/usr/local --bindir=/usr/local/bin build
ninja -C build install

cd /tmp

rm -rf ${WORKDIR}
