name: Build Puppy Main SFS + initrd (Hannah Montana Edition)

on:
  #schedule:
    #- cron: '0 2 */20 * *' # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:sid
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          apt-get install -y \
            busybox \
            squashfs-tools wget xz-utils ca-certificates desktop-file-utils openssl \
            wget kmod curl cpio coreutils python3 python3-pip unzip binutils patch

      - name: Building compiling puppy core applications
        shell: bash
        run: |
             . ./build-settings.cfg
             cp -rf ./puppy-source-builds /
             chmod +x ./external-tools/compile-puppy-core-apps.sh
             ./external-tools/compile-puppy-core-apps.sh
              mkdir -p puppy-core-apps-build
              cp -rf /usr/local/* ./puppy-core-apps-build/

      - name: Building debian puppy filesystem
        shell: bash
        run: |
        
              . ./DISTRO_SPECS

              echo "DISTRO_NAME=$DISTRO_NAME" >>  $GITHUB_ENV
              echo "DISTRO_VERSION=$DISTRO_VERSION" >>  $GITHUB_ENV
              echo "DISTRO_PUPPYSFS=$DISTRO_PUPPYSFS" >>  $GITHUB_ENV

              export TERM=xterm
              
              chmod +x ./01-build-debian-puppy.sh
              ./01-build-debian-puppy.sh
              
              . ./build-settings.cfg
            
              cp -rf ./puppy-core-apps-build/* $ROOTFS/usr/local/

              #Install hannah montana linux v26 theme
              git clone https://gitlab.com/DecaCagle/hannahmontanalinux26.git hannah-montana-linux

              for fld in color-schemes desktop-base icons plasma sddm wallpapers
              do
                cp -arf ./hannah-montana-linux/config/includes.chroot/usr/share/$fld $ROOTFS/usr/share/
              done

              cp -arf ./hannah-montana-linux/config/includes.chroot/etc/skel/.config $ROOTFS/etc/skel/
              
              chroot $ROOTFS /usr/lib/puppy/sbin/update-cache.sh y
              
      - name: Packing puppy filesystem into main sfs file
        shell: bash
        run: |      
              chmod +x ./03-pack-sfs.sh
              ./03-pack-sfs.sh
      
      - name: Process initrd
        shell: bash
        run: |              
              chmod +x ./04-process-initrd.sh
              ./04-process-initrd.sh
                 
      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_NAME }}-${{ env.DISTRO_VERSION }}-main-files
          path: |
                puppy-livecd-build/${{ env.DISTRO_PUPPYSFS }}
                puppy-livecd-build/initrd.xz
          compression-level: 0 

      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_NAME }}-${{ env.DISTRO_VERSION }}-initrd
          path: puppy-livecd-build/initrd.xz
          compression-level: 0 

      - name: Upload output build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTRO_PUPPYSFS }}
          path: puppy-livecd-build/${{ env.DISTRO_PUPPYSFS }}
          compression-level: 0           
