name: Build rEFInd

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential uuid-dev iasl nasm git python3 \
            python3-setuptools

      - name: Clone EDK2 (TianoCore)
        run: |
          git clone https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init

      - name: Build BaseTools
        run: |
          cd edk2        
          make -C BaseTools

      - name: Setup EDK2 environment
        run: |
          cd edk2
          source edksetup.sh
          echo "EDK2 setup done"

      - name: Download rEFInd source
        run: |
          wget -O refind.tar.gz "https://twds.dl.sourceforge.net/project/refind/0.14.2/refind-src-0.14.2.tar.gz?viasf=1"
          tar -xzf refind.tar.gz
          mv refind-0.14.2 RefindPkg

          cd RefindPkg

          sed -i -e 's#^refind,1,#refind,8,#g' ./refind-sbat.csv
          sed -i -e 's#^refind,1,#refind,8,#g' ./refind-sbat-local.csv

          sed -i -e 's#^refind.local,1,#refind.local,8,#g' ./refind-sbat-local.csv

      - name: Build rEFInd (X64)
        run: |
          cd edk2
          source edksetup.sh

          # Ensure Conf is initialized
          if [ ! -f Conf/tools_def.txt ]; then
            cp -r Conf/.template/* Conf/
          fi
          
          build -a X64 -t GCC5 -p ../RefindPkg/RefindPkg.dsc

      - name: Collect artifacts
        run: |
          mkdir -p artifacts
          find edk2/Build -name "*.efi" -exec cp {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: refind-efi
          path: artifacts/
